# 数据探索


In [1]:
import pandas as pd
import numpy as np

In [2]:
path='../avazu_data/'

In [3]:
 """
• id: ad identifier （广告 ID）
• click: 0/1 for non-click/click （是否被点击，其中 0 为不被点击，1 为不被点击，此列为目
标变量）
• hour: format is YYMMDDHH, so 14091123 means 23:00 on Sept. 11, 2014 UTC. （时间）
• C1 -- anonymized categorical variable （类别型变量）
• banner_pos （广告位置）
• site_id （站点 ID）
• site_domain （站点领域）
• site_category （站点类别）
• app_id （APP ID）
• app_domai
• C14-C21 -- anonymized categorical variables （类别型变量）
 """

#读取数据
train = pd.read_csv(path+"train_01.csv")
train.head()

id  click      hour    C1  banner_pos   site_id site_domain  \
0  1.000009e+18      0  14102100  1005           0  1fbe01fe    f3845767   
1  1.000017e+19      0  14102100  1005           0  1fbe01fe    f3845767   
2  1.000037e+19      0  14102100  1005           0  1fbe01fe    f3845767   
3  1.000064e+19      0  14102100  1005           0  1fbe01fe    f3845767   
4  1.000068e+19      0  14102100  1005           1  fe8cc448    9166c161   

  site_category    app_id app_domain ...  device_type device_conn_type    C14  \
0      28905ebd  ecad2386   7801e8d9 ...            1                2  15706   
1      28905ebd  ecad2386   7801e8d9 ...            1                0  15704   
2      28905ebd  ecad2386   7801e8d9 ...            1                0  15704   
3      28905ebd  ecad2386   7801e8d9 ...            1                0  15706   
4      0569f928  ecad2386   7801e8d9 ...            1                0  18993   

   C15  C16   C17  C18  C19     C20  C21  
0  320   50  1722    0   35      -1   79  
1  320   50  1722    0   35  100084   79  
2  320   50  1722    0   35  100084   79  
3  320   50  1722    0   35  100084   79  
4  320   50  2161    0   35      -1  157  

[5 rows x 24 columns]

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499999 entries, 0 to 499998
Data columns (total 24 columns):
id                  499999 non-null float64
click               499999 non-null int64
hour                499999 non-null int64
C1                  499999 non-null int64
banner_pos          499999 non-null int64
site_id             499999 non-null object
site_domain         499999 non-null object
site_category       499999 non-null object
app_id              499999 non-null object
app_domain          499999 non-null object
app_category        499999 non-null object
device_id           499999 non-null object
device_ip           499999 non-null object
device_model        499999 non-null object
device_type         499999 non-null int64
device_conn_type    499999 non-null int64
C14                 499999 non-null int64
C15                 499999 non-null int64
C16                 499999 non-null int64
C17                 499999 non-null int64
C18                 499999 non-null in

In [5]:
train.describe()

id          click          hour             C1  \
count  4.999990e+05  499999.000000  4.999990e+05  499999.000000   
mean   9.314822e+18       0.164072  1.410210e+07    1005.034018   
std    5.213417e+18       0.370342  9.156394e-01       0.966679   
min    9.984920e+12       0.000000  1.410210e+07    1001.000000   
25%    4.828055e+18       0.000000  1.410210e+07    1005.000000   
50%    9.794432e+18       0.000000  1.410210e+07    1005.000000   
75%    1.347337e+19       0.000000  1.410210e+07    1005.000000   
max    1.844670e+19       1.000000  1.410210e+07    1012.000000   

          banner_pos    device_type  device_conn_type            C14  \
count  499999.000000  499999.000000     499999.000000  499999.000000   
mean        0.217276       1.036694          0.223636   18193.190726   
std         0.443134       0.489694          0.669603    3343.520110   
min         0.000000       0.000000          0.000000     375.000000   
25%         0.000000       1.000000          0.000000   15706.000000   
50%         0.000000       1.000000          0.000000   18993.000000   
75%         0.000000       1.000000          0.000000   20632.000000   
max         7.000000       5.000000          5.000000   21705.000000   

                 C15            C16            C17            C18  \
count  499999.000000  499999.000000  499999.000000  499999.000000   
mean      319.183990      56.561381    2031.634981       1.109154   
std        21.037095      36.185072     417.209113       1.277893   
min       120.000000      20.000000     112.000000       0.000000   
25%       320.000000      50.000000    1722.000000       0.000000   
50%       320.000000      50.000000    2161.000000       0.000000   
75%       320.000000      50.000000    2351.000000       3.000000   
max      1024.000000    1024.000000    2497.000000       3.000000   

                 C19            C20            C21  
count  499999.000000  499999.000000  499999.000000  
mean      201.528833   42639.972412      74.051028  
std       273.749361   49497.507218      40.835671  
min        33.000000      -1.000000      13.000000  
25%        35.000000      -1.000000      48.000000  
50%        39.000000      -1.000000      61.000000  
75%       297.000000  100084.000000      79.000000  
max      1835.000000  100248.000000     195.000000

# 1、处理hour特征，格式为YYMMDDHH
数据为21-31，共11天的数据

In [6]:
train['day']=np.round(train.hour % 10000 / 100)
train['hour1'] = np.round(train.hour % 100)
train['day_hour'] = (train.day.values - 21) * 24 + train.hour1.values
train['day_hour_prev'] = train['day_hour'] - 1
train['day_hour_next'] = train['day_hour'] + 1

#  app_id

In [7]:
train['app_or_web'] = 0
#如果app_id='ecad2386',mobile_dev=1
train.ix[train.app_id.values=='ecad2386', 'app_or_web'] = 1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until


In [8]:
#串联app_id和site_id
train['app_site_id'] = np.add(train.app_id.values, train.site_id.values)

In [9]:
train['dev_id_ip'] = pd.Series(np.add(train.device_id.values , train.device_ip.values)).astype('category').values.codes

In [10]:
train.head()

id  click      hour    C1  banner_pos   site_id site_domain  \
0  1.000009e+18      0  14102100  1005           0  1fbe01fe    f3845767   
1  1.000017e+19      0  14102100  1005           0  1fbe01fe    f3845767   
2  1.000037e+19      0  14102100  1005           0  1fbe01fe    f3845767   
3  1.000064e+19      0  14102100  1005           0  1fbe01fe    f3845767   
4  1.000068e+19      0  14102100  1005           1  fe8cc448    9166c161   

  site_category    app_id app_domain    ...         C20  C21   day hour1  \
0      28905ebd  ecad2386   7801e8d9    ...          -1   79  21.0     0   
1      28905ebd  ecad2386   7801e8d9    ...      100084   79  21.0     0   
2      28905ebd  ecad2386   7801e8d9    ...      100084   79  21.0     0   
3      28905ebd  ecad2386   7801e8d9    ...      100084   79  21.0     0   
4      0569f928  ecad2386   7801e8d9    ...          -1  157  21.0     0   

   day_hour  day_hour_prev  day_hour_next  app_or_web       app_site_id  \
0       0.0           -1.0            1.0           1  ecad23861fbe01fe   
1       0.0           -1.0            1.0           1  ecad23861fbe01fe   
2       0.0           -1.0            1.0           1  ecad23861fbe01fe   
3       0.0           -1.0            1.0           1  ecad23861fbe01fe   
4       0.0           -1.0            1.0           1  ecad2386fe8cc448   

   dev_id_ip  
0     148269  
1     110010  
2     125739  
3     153812  
4     109872  

[5 rows x 32 columns]

In [11]:
import sys
sys.path.append('D:\GitHub\jhye_tool\ml')
sys.path.append('D:\GitHub\jhye_tool')


In [12]:
filter_t1 = np.logical_and(train.day.values != 20, train.day.values < 31)

In [16]:
from ml_utils import *


In [17]:
calcTVTransform(train,'app_or_web','click',10,filter_t1)

2018-06-11 11:10:32,440 - DEBUG - ml_utils.py:220 - 0.16407232814465628
2018-06-11 11:10:32,441 - DEBUG - ml_utils.py:224 - 1
2018-06-11 11:10:32,593 - DEBUG - ml_utils.py:237 - 1
2018-06-11 11:10:32,593 - DEBUG - ml_utils.py:238 - 2


{'cnt': array([], dtype=int64), 'exp': array([], dtype=float64)}

In [15]:
train.ix[filter_t1, 'click'].mean()

0.16407232814465628

In [39]:
org_idx = np.zeros(train.site_id.size, dtype=np.int)

In [40]:
org_idx.shape

(499999,)

In [41]:
_ord = np.lexsort((train.site_id.values, train.site_id.values))

In [42]:
_ord

array([ 36992, 324971,  74744, ..., 379599, 427572, 472669], dtype=int64)

In [43]:
org_idx

array([0, 0, 0, ..., 0, 0, 0])

In [46]:
np.asarray(range(train.site_id.size))

array([     0,      1,      2, ..., 499996, 499997, 499998])

In [44]:
org_idx[_ord] = np.asarray(range(train.site_id.size))

In [48]:
org_idx[324971]

1